name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

env:
  CARGO_INCREMENTAL: 0
  CARGO_PROFILE_RELEASE_LTO: "fat"
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/checkout
      - uses: actions/checkout@v7

      # https://github.com/pnpm/action-setup
      - uses: pnpm/action-setup@v6

      # https://github.com/actions/setup-node
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          package-manager-cache: false

      - name: Install Node dependencies
        run: pnpm install --frozen-lockfile

      - name: Install Rust
        run: rustup show

      - name: Cache Cargo
        uses: actions/cache@v6
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: lint
        run: |
          cargo fmt -- --check
          cargo clippy -- -D warnings

      - name: test
        run: |
          cargo test
          node --run typecheck
          node --run build
          node --run test:e2e
